<?php

namespace Snap\Lib\Form;

interface Test {
	/**
	 * Returns true if valid input, false otherwise
	 */
	public function isValid( $value );
	
	/**
	 * Returns the error to be generated by the test
	 */
	public function getError();
}