<?php

namespace Snap\Lib\Form;

interface Validation {
	/**
	 * Returns set of inputs if errored, null if ok
	 */
	public function checkForErrors( $inputs );
	
	/**
	 * Returns the error to be generated by the test
	 */
	public function getError();
}